[project]
name = "linearequationssystems"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.3",
    "scipy>=1.15.2",
    "streamlit>=1.43.1",
    "matplotlib>=3.10.1",
]
